apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
spec:
  project: infra
  source:
    chart: pihole
    targetRevision: "2.11.1"
    repoURL: https://mojo2600.github.io/pihole-kubernetes/
    helm:
      releaseName: pihole
      values: |
        serviceDns:
          type: LoadBalancer
        persistentVolumeClaim:
          enabled: true
        ingress:
          enabled: true
          hosts:
            - pihole.home-internal.marceligrabowski.pl
            - pihole.home
  destination:
    server: "https://kubernetes.default.svc"
    namespace: infra
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true