---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: naszkle

commonLabels:
  app: na-szkle-saleor-platform

images:
  - name: saleor-image
    newName: skymoore/saleor
    newTag: "3.8.4"
  - name: saleor-dashboard-image
    newName: skymoore/saleor-dashboard
    newTag: "3.8.4"

resources:
  - https://raw.githubusercontent.com/skymoore/saleor-platform-k8s-kustomize/main/base/kustomization.yml
  - https://raw.githubusercontent.com/skymoore/saleor-platform-k8s-kustomize/main/saleor/kustomization.yml
  - https://raw.githubusercontent.com/skymoore/saleor-platform-k8s-kustomize/main/saleor-dashboard/kustomization.yml